[[directories]]
name = "01 PROJECTS" # Stores notes and files for active, time-bound tasks or deliverables.
readme_content = """
# 01 PROJECTS

Stores notes and files for active, time-bound tasks or deliverables.\
"""

[[directories]]
name = "02 AREAS" # Contains ongoing responsibilities or areas of interest.
readme_content = """
# 02 AREAS

Contains ongoing responsibilities or areas of interest.\
"""

[[directories]]
name = "03 RESOURCES" # Holds general reference materials and reusable templates.
readme_content = """
# 03 RESOURCES

Holds general reference materials and reusable templates.\
"""

[[directories]]
name = "04 ARQUIVE" # Keeps inactive projects and outdated resources for future reference.
readme_content = """
# 04 ARQUIVE

Keeps inactive projects and outdated resources for future reference.\
"""
