[[directories]]
name = "01 PROJECTS"
readme_content = "# PROJECTS\n\nStores notes and files for active, time-bound tasks or deliverables."

[[directories]]
name = "02 AREAS"
readme_content = "# AREAS\n\nContains ongoing responsibilities or areas of interest."

[[directories]]
name = "03 RESOURCES"
readme_content = "# RESOURCES\n\nHolds general reference materials and reusable templates."

[[directories]]
name = "04 ARQUIVE"
readme_content = "# ARQUIVE\n\nKeeps inactive projects and outdated resources for future reference."
