[[directories]]
name = "01 PROJECTS"
readme_content = """
# PROJECTS

Stores notes and files for active, time-bound tasks or deliverables."""

[[directories]]
name = "02 AREAS"
readme_content = """
# AREAS

Contains ongoing responsibilities or areas of interest."""

[[directories]]
name = "03 RESOURCES"
readme_content = """
# RESOURCES

Holds general reference materials and reusable templates."""

[[directories]]
name = "04 ARQUIVE"
readme_content = """
# ARQUIVE

Keeps inactive projects and outdated resources for future reference."""
